// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIxZ-_7f3vhZSgsIdzzLfTviRUu5xiMR8',
    appId: '1:17868364789:web:a427cd51e017dd316f9ebc',
    messagingSenderId: '17868364789',
    projectId: 'bahtareen-app',
    authDomain: 'bahtareen-app.firebaseapp.com',
    storageBucket: 'bahtareen-app.firebasestorage.app',
    measurementId: 'G-8BSTX35X2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkaQkSMWy3xCmJ2ytGRZDsT3S3KZDH3U',
    appId: '1:17868364789:android:3b03ae6e212efafc6f9ebc',
    messagingSenderId: '17868364789',
    projectId: 'bahtareen-app',
    storageBucket: 'bahtareen-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-xfqdejRTDxh1mrzqnqaZs6a6OBF5hM',
    appId: '1:17868364789:ios:09c181c745906b986f9ebc',
    messagingSenderId: '17868364789',
    projectId: 'bahtareen-app',
    storageBucket: 'bahtareen-app.firebasestorage.app',
    iosBundleId: 'com.example.bahtareen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-xfqdejRTDxh1mrzqnqaZs6a6OBF5hM',
    appId: '1:17868364789:ios:09c181c745906b986f9ebc',
    messagingSenderId: '17868364789',
    projectId: 'bahtareen-app',
    storageBucket: 'bahtareen-app.firebasestorage.app',
    iosBundleId: 'com.example.bahtareen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIxZ-_7f3vhZSgsIdzzLfTviRUu5xiMR8',
    appId: '1:17868364789:web:aa3ac852ea91d4c56f9ebc',
    messagingSenderId: '17868364789',
    projectId: 'bahtareen-app',
    authDomain: 'bahtareen-app.firebaseapp.com',
    storageBucket: 'bahtareen-app.firebasestorage.app',
    measurementId: 'G-ZSMNCTLMQ9',
  );

}